get:
  summary: Gets qc_security criteria.
  description: >
    Obtains info about the qc_security criteria as defined in JePL.
  operationId: getCriteriaSecurity
  tags:
    - criteria
  responses:
    '200':
      description: Array of all supported criteria.
      content:
        application/json:
          schema:
            type: object
            properties:
              repos:
                type: array
                items:
                  $ref: ../components/schemas/CriteriaRepository.yaml
