post:
  operationId: add_pipeline
  summary: Creates a pipeline.
  description: >
    Provides a ready-to-use Jenkins pipeline based on the v2 series of
    jenkins-pipeline-library.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/schemas/Pipeline.yaml'
  responses:
    '201':
      description: Created
get:
  operationId: get_pipelines
  summary: Gets pipeline IDs.
  description: >
    Returns the list of IDs for the defined pipelines.
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/Pipeline.yaml'
