get:
  operationId: get_pipeline_composer
  summary: Gets composer configuration used by the pipeline.
  parameters:
    - in: path
      name: pipeline_id
      description: ID of the pipeline to get
      required: true
      schema:
        type: string
  description: >
    Returns the content of JePL's docker-compose.yml file.
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/JePL_composer.yaml'
    '400':
      description: Invalid pipeline ID supplied
    '404':
      description: Pipeline not found
