type: object
properties:
  project_repos:
    type: array
    items:
      $ref: './Repository.yaml'
  credentials:
    type: array
    items:
      oneOf:
        - $ref: './Creds_user_pass.yaml'
        - $ref: './Creds_string.yaml'
        - $ref: './Creds_file.yaml'
        - $ref: './Creds_cert.yaml'
        - $ref: './Creds_ssh_user_private_key.yaml'
  sqa_criteria:
    type: array
    items:
      $ref: './CriterionBuild.yaml'
  environment:
    type: array
    items:
      $ref: './Environment.yaml'
