type: object
properties:
  project_repos:
    type: array
    items:
      $ref: './Repository.yaml'
  credentials:
    type: array
    items:
      $ref: './Credential.yaml'
  sqa_criteria:
    type: array
    items:
      $ref: './CriterionBuild.yaml'
