type: object
properties:
  config:
    type: object
    properties:
      project_repos:
        type: object
        $ref: './Repository.yaml'
      credentials:
        type: array
        items:
          $ref: './Creds_simplified.yaml'
  sqa_criteria:
    type: object
    $ref: './CriterionBuild.yaml'
  environment:
    $ref: './Environment.yaml'
  timeout:
    type: integer
    minimum: 1
