type: object
properties:
  id:
    type: integer
    format: uuid
    example: dd7d8481-81a3-407f-95f0-a2f1cb382a4b
  config_data:
    type: array
    items:
      $ref: './JePL_config.yaml'
  composer_data:
    $ref: './JePL_composer.yaml'
  jenkinsfile_data:
    $ref: './JePL_jenkinsfile.yaml'
