type: object
properties:
  id:
    type: integer
    format: uuid
  config_data:
    type: array
    items:
      $ref: './JePL_config.yaml'
  composer_data:
    $ref: './JePL_composer.yaml'
  jenkinsfile_data:
    $ref: './JePL_jenkinsfile.yaml'
