type: object
properties:
  service_id:
    type: string
    example: 'checkstyle'
  image:
    type: string
  hostname:
    type: string
  volumes:
    type: array
    items:
      type: object
      properties:
        volume_type:
          type: string
          enum: [bind]
        volume_source:
          type: string
        volume_target:
          type: string
  command:
    type: string
