type: object
additionalProperties:
  type: object
  properties:
    image:
      type: object
      properties:
        name:
          type: string
        push:
          type: boolean
    hostname:
      type: string
    volumes:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum: [bind]
          source:
            type: string
          target:
            type: string
    command:
      type: string
example:
  checkstyle:
    image:
      name: checkstyle/maven-builder-image
      push: true
    hostname: checkstyle-host
    volumes:
    - source: ./
      target: ./simple-java-app
      type: bind
    command: sleep 600000
