type: object
additionalProperties:
  type: object
  properties:
    build:
      type: object
      properties:
        context:
          type: string
        dockerfile:
          type: string
        args:
          type: object
          additionalProperties:
            type: string
    image:
      type: object
      properties:
        name:
          type: string
        registry:
          type: object
          properties:
            push:
              type: boolean
            url:
              type: string
              format: uri
            credential_id:
              type: string
      required:
        - name
    hostname:
      type: string
    volumes:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum: [bind]
          source:
            type: string
          target:
            type: string
    command:
      type: string
    environment:
      $ref: './Environment.yaml'
    oneshot:
      type: boolean
      default: true
example:
  checkstyle:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
    image:
      name: checkstyle/maven-builder-image
      registry:
        push: true
        url: https://hub.docker.com/
        credential_id: my-dockerhub-cred
    hostname: checkstyle-host
    volumes:
    - source: ./
      target: ./simple-java-app
      type: bind
    command: sleep 600000
