type: object
properties:
  service_id:
    type: string
    example: 'checkstyle'
  image:
    type: string
    example: 'checkstyle/maven-builder-image'
  hostname:
    type: string
    example: 'checkstyle-host'
  volumes:
    type: array
    items:
      type: object
      properties:
        volume_type:
          type: string
          enum: [bind]
        volume_source:
          type: string
          example: './'
        volume_target:
          type: string
          example: './simple-java-app'
  command:
    type: string
    example: 'sleep 600000'
