type: object
additionalProperties:
  type: object
  properties:
    image:
      type: string
    hostname:
      type: string
    volumes:
      type: array
      items:
        type: object
        properties:
          volume_type:
            type: string
            enum: [bind]
          volume_source:
            type: string
          volume_target:
            type: string
    command:
      type: string
example:
  checkstyle:
    image: checkstyle/maven-builder-image
    hostname: checkstyle-host
    volumes:
    - volume_source: ./
      volume_target: ./simple-java-app
      volume_type: bind
    command: sleep 600000
