config:
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      sqaaas-api-spec:
        container: node
        commands:
          - /sqaaas-api-spec/.git_credential_helper.sh get
          - git config --global user.name "Pablo Orviz"
          - git config --global user.email "orviz@ifca.unican.es"
          - npm --prefix /sqaaas-api-spec install
          - npm --prefix /sqaaas-api-spec run deploy
