config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/foo:
      branch: master
      repo: https://github.com/foo
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Sty:
    repos:
      github.com/foo:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-seashell-slug.sh
        container: qc.sty_sleazy-cinnabar-flamingo
timeout: 600
