config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-teal-snail.sh
        container: qc.doc_pasty-lime-caterpillar
      github.com/eosc-synergy/sqaaas-api-spec__2:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-burgundy-dogfish.sh
        container: qc.doc_chummy-asparagus-drever
timeout: 600
