config:
  credentials: []
  project_repos:
    github/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.sty_stuffy-peach-tiger
timeout: 600
