config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/safdadsf.sqaaas:
      branch: main
      repo: https://github.com/eosc-synergy/safdadsf.sqaaas
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Sty:
    repos:
      github.com/eosc-synergy/safdadsf.sqaaas:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-heliotrope-coyote.sh
        container: qc.sty_snoopy-mauve-reindeer
timeout: 600
