config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: staging
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-seashell-caracal.sh
        container: qc.doc_slaphappy-fuchsia-moth
      github.com/eosc-synergy/sqaaas-api-spec__2:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-corn-newfoundland.sh
        container: qc.doc_trippy-rust-maltese
timeout: 600
