config:
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      sqaaas-api-spec:
        container: node
        commands:
          - npm --prefix /sqaaas-api-spec install
          - npm --prefix /sqaaas-api-spec run build
          - > 
            env GIT_ASKPASS=/sqaaas-api-spec/.git_credential_helper.sh
            npm --prefix /sqaaas-api-spec run deploy --
            --user="Pablo Orviz <orviz@ifca.unican.es>"
            --repo=https://${GIT_USER}@github.com/eosc-synergy/sqaaas-api-spec
